### ISSUE TITLE
Rename organisation

### ISSUE THREAD

**Issue by dahacouk** [kendraio/kendra_home#24]
I want to rename the https://github.com/kendrainitiative to be https://github.com/kendraio

We are rebranding Kendra Initiative URLs. The new domain for Kendra Home will be *http://www.kendra.io*

All social media and links will be named *kendraio*. We already have:
https://www.facebook.com/kendraio
https://www.linkedin.com/company/kendraio
https://plus.google.com/+kendraio
https://www.youtube.com/c/kendraio

I can rename the *Kendra Initiative* organisation at
https://github.com/organizations/kendrainitiative/settings/profile
and we get the following warnings:
* Unexpected bad things will happen if you don't read this!
* We will create redirects for your repositories (web and git access).
* You will need to update your local repositories to point to the new location.
* Renaming may take a few minutes to complete.

Seems straightforward. Any issues with this @iAugur @darrenmothersele @BBGuy @andystiller @klokie ?

**Comment by iAugur** [comment]
So long as we all have an uptodate repo locally and have no local changes pending - then all we need to do is update our 'origins' locally and all should be good - I think?

**Comment by dahacouk** [comment]
OK. Great. Let me know when you've both done this and I'll make the change.

**Comment by BBGuy** [comment]
My local repo is clean, I think @andystiller pushed his changes on Tuesday but even if not we can work around it.
so go ahead from the Brighton team.

**Comment by iAugur** [comment]
I have updated mine - so good to go for me too

**Comment by dahacouk** [comment]
Done. Thanks guys. The redirects seem to work too. Cheers!
