### ISSUE TITLE
Kendra Home issues not working...

### ISSUE THREAD

**Issue by dahacouk** [kendraio/kendra_home#33]
Can we figure out what's going wrong with:
https://www.kendra.io/node/add/kendra-issue
?

For instance, from:
https://www.kendra.io/kendra-hub/partners
Click on "file an issue" and see what I mean.

**Comment by iAugur** [comment]
I have fixed this by unistalling the redirect module and reinstalling it.
It had been disabled before without uninstalling it which had messed the registry
so i have rebuilt the reg and reinstalled the module and all seems fine 
can you test and close if satisfied

**Comment by dahacouk** [comment]
Many thanks! Closing!

**Comment by BBGuy** [comment]
ops committed to wrong issue should be #20
