### ISSUE TITLE
Module security updates

### ISSUE THREAD

**Issue by andystiller** [kendraio/kendra_home#34]
The following modules have security updates that need to be reviewed, tested and applied.

- [x] Views
- [x] Safeword
- [x] Rules Link
- [x] Date
- [x] Chaos tool suite

**Comment by andystiller** [comment]
I have updated the version of the Views, Entity and Ctools modules to a new branch #34 for testing.

**Comment by andystiller** [comment]
I have updated the date module and tested by editing an event.

**Comment by andystiller** [comment]
I have applied the security updates for the Rules link a Safeword modules. I have tested Rules link by adding an organisation and assigning it to my profile.

**Comment by andystiller** [comment]
## Deploy to dev
- [ ] Merge branch 34 into dev
- [ ] Update database (drush updatedb)
- [ ] Clear caches
- [ ] Test
## Go Live
- [ ] Merge dev branch into master
- [ ] Update database (drush updatedb)
- [ ] Clear caches
- [ ] Test

**Comment by dahacouk** [comment]
@andystiller Any idea how I "removed the in progress label x minutes ago" (see above)? I didn't touch it. Is there an automated something going on?

**Comment by BBGuy** [comment]
@dahacouk not sure how but as its closed its no longer in progress so I think all is good :)

**Comment by andystiller** [comment]
@dahacouk I closed the issue as @BBGuy had put all the updates listed in the issue on the live site. I assume that the change of label must be automatic if it was changed by you.
