### ISSUE TITLE
Users can't see registration errors

### ISSUE THREAD

**Issue by dahacouk** [kendraio/kendra_home#41]
I attempt to register at https://www.kendra.io . I fill out the form badly. I get an error when I hit the "Create new account". The page reloads showing the top of the page and I can't see the form or the error because my browser window is too small to contain the whole page. Should we have something like https://www.kendra.io/#register that people get sent back to if there's an error so they can actually see it?

**Comment by BBGuy** [comment]
@dahacouk I am not sure I understand the issue. can you show a screenshot of how it looks when it goes wrong

**Comment by dahacouk** [comment]
@BBGuy I've updated the issue to make it clearer. Hint: make your browser have a small window so that the registration form is below out of view. Yeah?

**Comment by BBGuy** [comment]
@dahacouk I have re positioned the messages so they are at the top of the page under the banner. 
Can you test and see if this resolves the issue

**Comment by dahacouk** [comment]
That'll do for the moment. Thanks!
