### ISSUE TITLE
Quick fix to theme/CSS...

### ISSUE THREAD

**Issue by dahacouk** [kendraio/kendra_home#42]
So... I know it's all my fault. I've learnt another big lesson: don't do any styling until the basic functionality is there. And also make sure any styling is done site wide so that we don't end up in the situation we are in now where some pages are full width and some pages are not.

The main problem starts at https://www.kendra.io/user (as a non-admin user) the 4 tabs at the top go to pages where the tabs disappear. We need to correct this now because I want to start importing people now.

I need a quick fix.

**Comment by dahacouk** [comment]
@BBGuy perhaps linked to this issue could be a problem when I save my profile or account (as a non-admin user) the "The changes have been saved" is not viewable.

I'm wondering if we should change the themes (public and admin) to be the same so this is easier to debug. Eat our own dog food?

**Comment by dahacouk** [comment]
Also add in all these pages we need to fix quickly:
* https://www.kendra.io/users
* https://www.kendra.io/orgs
* https://www.kendra.io/users/countries

**Comment by iAugur** [comment]
I have updated the layout on all of these pages.
I think we should also:
* cache these pages
* Use pagers on these pages (e.g. in pages of 20)
* add a common navigation element to link the pages together

**Comment by iAugur** [comment]
I will add the default page elements (tabs, messages) to the page template and remove them from the panel-pages. Then we will have a theme that works bot for admin and public.

**Comment by dahacouk** [comment]
If you can get edit tabs on the pages such as https://www.kendra.io/kendra-hub/partners then that would be great tooooooo! ;-)

**Comment by iAugur** [comment]
Done!

**Comment by iAugur** [comment]
I have updated the theme to show default system elements on all pages.
Updated all page manager (panels) pages to reflect this (e.g. not double up tabs, message etc)
This now allows us to use the same theme for the admin as the public site

**Comment by iAugur** [comment]
If you are happy with this - can you close the issue

**Comment by dahacouk** [comment]
Can we have...

- [ ] The tab or to be:
* By name (was "Users")
* By organisation
* By country

- [ ] The page titles to be:
* By name (was "Members: Users")
* By organisation
* By country (was "Members: Users - Countries")

- [ ] Breadcrumb listed for "By name". But I have a bad feeling about this one! :confused:

**Comment by dahacouk** [comment]
Looks good to me thanks!
