### ISSUE TITLE
Don't show add organisation button when not logged in

### ISSUE THREAD

**Issue by dahacouk** [kendraio/kendra_home#47]
Don't show add organisation button when not logged in as in https://www.kendra.io/users/dahacouk

![window_and_sabine_jacques___kendra_initiative](https://cloud.githubusercontent.com/assets/201752/8065313/96b492d6-0ed8-11e5-8b8a-35957eec8881.png)

**Comment by iAugur** [comment]
Don't think you can view a user if not logged in?

**Comment by iAugur** [comment]
The button is in the views footer
I have wrapped it in php to check if the user is authenticated.
```php
<?php
global $user;
if ($user->uid)  {
$straddorg = '<div class="pull-right col-sm-6"><a href = "/user/!1/add-org" role="button" class="btn btn-success"><span class="glyphicon glyphicon-plus"></span>Add organisation</a></div>';
print $straddorg;
}
```

**Comment by iAugur** [comment]
this is now live - close if happy

**Comment by dahacouk** [comment]
Thanks!
