### ISSUE TITLE
Remove footer from simplenews newsletter

### ISSUE THREAD

**Issue by dahacouk** [kendraio/kendra_home#49]
There is an unsubscribe footer hardcoded into the simpleness newsletter. Please can you remove this? I’ve found this https://www.drupal.org/node/321012 if it helps.

**Comment by iAugur** [comment]
Added override template to theme and removed unsubscribe element from footer
tested on staging - please test live and close if done

**Comment by dahacouk** [comment]
Thanks!

**Comment by iAugur** [comment]
Add override for body template to remove title

**Comment by iAugur** [comment]
Added, tested and working
