### ISSUE TITLE
Simplenews headers sent with "staging" reference

### ISSUE THREAD

**Issue by dahacouk** [kendraio/kendra_home#52]
The newsletter email is being sent out with a header:

```
List-Unsubscribe: <https://www-staging.kendra.io/newsletter/confirm/remove...
```

I suspect this got changed when template work was done in #49 because it started off being "www-live" which is also wrong. Should just be "www".

Just need to find config that relates to that. But suspect it is in template.

**Comment by iAugur** [comment]
Can you check this - as i suspect it was only in emails sent from the staging server. i.e. it puts the host header for the server source.
Looking at the raw source for the newsletter i received all is OK

**Comment by dahacouk** [comment]
Here's some stats:
* 322 emails sent from *https://www-live.kendra.io* and some with capitalised title that @iAugur removed early on in the mailout.
 * But I really don't get why any went out as *www-live*.
  * Those that went out as *www-live* don't seem to have gone out as *www*. But only looked for a couple of accounts.
* 80 emails sent from *https://www-dev.kendra.io*.
* 161 emails sent from *https://www-staging.kendra.io*.
So some people got 3 emails.

Anyway we should move to MailChimp. I'm convinced! :grinning:

**Comment by dahacouk** [comment]
Closing as we moved to MailChimp.
