### ISSUE TITLE
Check password reset is working

### ISSUE THREAD

**Issue by dahacouk** [kendraio/kendra_home#53]
We've had reports that password reset is not working correctly.

> No. I am not able to get a new password.  I get stuck in a loop. 
> 1. request new password
> 2. email arrives
> 3. email arrives with link for new password
> 4. I supply a new password, meeting all the criteria and both match
> 5. Click Logon 
> I then get an error msg 
>> You have tried to use a one-time login link that has either been used or is no longer valid. Please request a new one using the form below.
>
> I request a new one and ...

Perhaps look at https://www.drupal.org/project/simple_pass_reset

**Comment by BBGuy** [comment]
I had a few issues testing dev will not send emails for some reason:
> Unable to send e-mail. Contact the site administrator if the problem persists.

On live worked ok but got a  Warning
> Warning: Missing argument 4 for user_pass_rehash(), called in /var/www/www.kendra.io/live/htdocs/sites/all/modules/contrib/prlp/prlp.module on line 112 and defined in user_pass_rehash() (line 2386 of /var/www/www.kendra.io/live/htdocs/modules/user/user.module).

**Comment by BBGuy** [comment]
@dahacouk can you test again.

**Comment by dahacouk** [comment]
On live I also get:

> You have tried to use a one-time login link that has either been used or is no longer valid. Please request a new one using the form below.

So, I confirm this is throwing people into a loop.

![reset_password___kendra_initiative](https://cloud.githubusercontent.com/assets/201752/8235966/1e421e16-15dd-11e5-982f-631b2a77c217.png)

**Comment by BBGuy** [comment]
@dahacouk  managed to recreate using testt9@daha.co.uk (user 3g4e18)  updated to testt9@blue-bag.com on my local copy for testing. 

Looks like this may be solved by upgrading Password Reset Landing Page (PRLP) https://www.drupal.org/project/prlp

**Comment by BBGuy** [comment]
George sorted emails on dev and after upgraded the PRLP module the one time login link works with 3g4e18 and without warnings.

**Comment by BBGuy** [comment]
Pushed to live and working. @dahacouk can you test using testt9@daha.co.uk and close if you are happy

**Comment by dahacouk** [comment]
Tested with other accounts. Thanks!
