### ISSUE TITLE
Mandrill Settings

### ISSUE THREAD

**Issue by iAugur** [kendraio/kendra_home#65]
Reviewing the settings on Mandrill I have noticed:
- [x] The SPF record requires updating from: 
```
v=spf1 include:spf.messagingengine.com -all
to 
v=spf1 include:spf.messagingengine.com include:spf.mandrillapp.com -all
```
- [ ] The domain requires validation - send an email and validate

**Comment by dahacouk** [comment]
Please can you specific to which domain(s) you are talking about?

**Comment by iAugur** [comment]
Kendra.org.uk - If you are about - I will kickstart the process - you just have to verify the email they send - i will send it to daniel@kendra.org.uk

**Comment by dahacouk** [comment]
Done! I'm also adding *kendra.io* for future use. Thanks!

**Comment by iAugur** [comment]
@dahacouk - great - i have updated the SPF for that too - and  all verified ; )

**Comment by dahacouk** [comment]
Ach! I was just updating SPF too. No worries! ;-) All done. Well done and closing.
