### ISSUE TITLE
Shutting down www.kendra.org.uk

### ISSUE THREAD

**Issue by dahacouk** [kendraio/kendra_home#67]
When ready...

- [x] Archive www.kendra.org.uk and scrape it using [SiteSucker](http://ricks-apps.com/osx/sitesucker/index.html) or something like that.

- [x] Redirect xxxxx.kendra.org.uk/xxxxx to xxxxx.kendra.io/xxxxx with specific 301 redirects that I can administer easily. Also monitor what subdomains and URLs in xxxxx.kendra.org.uk are being requested, number of times, from where, with hit or no hit.

**Comment by dahacouk** [comment]
In the short term I want to rename www.kendra.org.uk to something secret and do the redirects now.

**Comment by iAugur** [comment]
[ ] Investigate import redirects
[ ] create list of source url (kendra.org.uk) -> target urls (kendra.io)
[ ] Update vhost for kendra.io to accept kendra.org.uk
[ ] Update DNS for kendra.org.uk -> kendra.io IP

**Comment by dahacouk** [comment]
@iAugur I've done 2 tasks: archived the site and created a redirect spreadsheet (still in progress). What I need now is an interface to administer and view counts for redirects. Your turn.

[Just realised that ticking a box and editing a comment doesn't kick off a notification. Hence this comment.]

**Comment by iAugur** [comment]
- [ ] Implement global redirect
- [ ] redirect import

**Comment by andystiller** [comment]
I have installed global redirect, path redirect import and updated the redirect module. To import the language to 'und' for the import https://www.drupal.org/node/2172311.

**Comment by iAugur** [comment]
I have added a specific vhost for kendra.org.uk that:
 - rewrites all traffic from www.kendra.org.uk/somepage -> www.kendra.io/somepage
 - rewrites traffic to www.kendra.org.uk/ -> www.kendra.io/kendraorguk

So ... Once you are happy and have your rewrites in place we can switch over the DNS

**Comment by dahacouk** [comment]
I've been thinking that a better way could be to prepend **wwwkendraorguk** to all incoming paths and then it would be easy to capture with a log search. And that doesn't make any difference to the rewriting. Yes?

So, kendra.org.uk and www.kendra.org.uk would:
* rewrite all traffic from www.kendra.org.uk/somepage -> www.kendra.io/wwwkendraorguk/somepage
* rewrite traffic to www.kendra.org.uk/ -> www.kendra.io/wwwkendraorguk
* rewrite traffic to kendra.org.uk/ -> www.kendra.io/wwwkendraorguk

Yes?

**Comment by dahacouk** [comment]
Wow! That's a lovely closed issue! Thanks @iAugur and @andystiller !
