### ISSUE TITLE
Favicon variants

### ISSUE THREAD

**Issue by iAugur** [kendraio/kendra_home#68]
We get a lot of 4040errors with browers (especially mobile devices) looking for favicon type files:
- apple-touch-icon-precomposed.png
- apple-touch-icon.png
etc

So I have created a full set for all devices and at the very least we should put these in the root of the site.
We could also add the metadata / links in the head to provide nice icons for when people pin tabs, save to homescreen etc
See the files in drop box and let me know what you think
https://www.dropbox.com/sh/809whnesfnlu6da/AABfP33IVdiWo6kxEPn8mdGta?dl=0

**Comment by dahacouk** [comment]
Wow! Awesome! Probably the last thing we need but great! ;-) I'm happy for you to proceed if you want.

**Comment by iAugur** [comment]
Gloss and design aside - the main motivation here is to reduce the 404 entries in the log ;)

**Comment by dahacouk** [comment]
Nice! ;-)

**Comment by andystiller** [comment]
I've added the 2 apple touch icons that cause most of the 404 entries and updated the theme to link to the main icon. I've also included a browserconfig.xml file and an icons folder for Windows 8 live tiles compatibility.

**Comment by iAugur** [comment]
I have moved the icons/ folder to msicons/ as icons/ has a special alias in apache.
I have commented out the alias in aliases.conf
