### ISSUE TITLE
When not logged in, "My Profile" link leads to a 404 Error page instead of "Register/Log-In" Page

### ISSUE THREAD

**Issue by lenapagel** [kendraio/kendra_home#83]
On the bottom of the landing page, there's a link to "My Profile". _If you're not already logged in_ it leads to a [404 Error, saying "Page Not Found"](https://www.kendra.io/not%20yet%20assigned). This should be leading to the [register/log-in page](https://www.kendra.io/user/login) instead, from which you then get redirected to your profile.  

<img width="1280" alt="kendraio homepage error" src="https://user-images.githubusercontent.com/64536095/80703465-20292c80-8ae3-11ea-8bf2-d5cd8174f45e.png">

**Comment by andystiller** [comment]
I will have a look at this early next week.

**Comment by andystiller** [comment]
I have added the menu per role module that allows the menu visibility to be set depending on the user role. The visibility is set on individual menu items.

Setting the my profile menu item to not be visible for anonymous users hides the menu item when not logged in. The only potential issue is Auth0 Token Based Authentication badge moves.

**Comment by andystiller** [comment]
The code is now live. I have configured the "My Profile" menu link to not be visible for anonymous users.

I have cleared all the caches and tested both logged in and not logged in.
