### ISSUE TITLE
Password reset not working

### ISSUE THREAD

**Issue by andystiller** [kendraio/kendra_home#84]
When a user receives an email with a link to login, the user can enter a new password.
Immediately afterwards, the text "You have tried to use a one-time login link that has either been used or is no longer valid" appears, even though the link is brand new.

The problem only occurs using the password reset page.
https://www.drupal.org/project/prlp/issues/3208362

Updating the PRLP modules should solve the issue.

**Comment by iAugur** [comment]
New release - https://www.drupal.org/project/prlp/releases/7.x-1.4 fixes this issue
Tested and deployed - confirmed working now
